'use client';
import {Pagination,Alert,Button,Spin} from 'antd';
import {useRouter,usePathname,useSearchParams} from 'next/navigation';
import {useQuery} from '@tanstack/react-query';
import type {TeacherPublicDetail,PricingPackageView,AvailabilityView,Review,PageMeta} from '@/shared/api/public';
import {getTeacherPackages,getTeacherReviews} from '@/shared/api/public';
import {TeacherPackagesTab} from '@/features/marketplace/components/TeacherPackagesTab';
import TrialRequestForm from '@/features/marketplace/components/TrialRequestForm';
import {MessageTeacherButton} from '@/features/chat/components/MessageTeacherButton';
const days:Record<string,string>={MONDAY:'Thứ hai',TUESDAY:'Thứ ba',WEDNESDAY:'Thứ tư',THURSDAY:'Thứ năm',FRIDAY:'Thứ sáu',SATURDAY:'Thứ bảy',SUNDAY:'Chủ nhật'};
export default function TeacherDetailClient({teacher,packages,availability,reviews,subjectOptions=[],errors=[]}:{teacher:TeacherPublicDetail;packages:{data:PricingPackageView[];meta:Partial<PageMeta>};availability:AvailabilityView[];reviews:{data:Review[];meta:Partial<PageMeta>};subjectOptions?:{id:string;name:string}[];errors?:string[]}){
 const router=useRouter();const pathname=usePathname();const search=useSearchParams();
 const packagePage=Math.max(0,Number(search.get('packagesPage')||0)); const reviewPage=Math.max(0,Number(search.get('reviewsPage')||0));
 const packageInitial={success:true,message:null,data:packages.data,errors:null,meta:{page:0,size:packages.meta.size||6,totalElements:packages.meta.totalElements||packages.data.length,totalPages:packages.meta.totalPages||1,hasNext:false,hasPrevious:false}};
 const reviewInitial={success:true,message:null,data:reviews.data,errors:null,meta:{page:0,size:reviews.meta.size||10,totalElements:reviews.meta.totalElements||reviews.data.length,totalPages:reviews.meta.totalPages||1,hasNext:false,hasPrevious:false}};
 const packageQuery=useQuery({queryKey:['public-teacher-packages',teacher.id,packagePage],queryFn:()=>getTeacherPackages(teacher.id,packagePage,6),initialData:packageInitial,enabled:packagePage>0,staleTime:300_000});
 const reviewQuery=useQuery({queryKey:['public-teacher-reviews',teacher.id,reviewPage],queryFn:()=>getTeacherReviews(teacher.id,reviewPage,10),initialData:reviewInitial,enabled:reviewPage>0,staleTime:60_000});
 const packageData=packageQuery.data||packageInitial; const reviewData=reviewQuery.data||reviewInitial;
 const page=(key:string,n:number,anchor:string)=>{const q=new URLSearchParams(search.toString());q.set(key,String(n));router.push(pathname+'?'+q.toString()+'#'+anchor,{scroll:false});};
 const error=(key:string)=>errors.includes(key)?<Alert type="error" title="Chưa tải được dữ liệu" action={<Button onClick={()=>router.refresh()}>Thử lại</Button>}/>:null;
 return <><nav className="tm-detail-nav" aria-label="Các phần hồ sơ"><a href="#about">Giới thiệu</a><a href="#packages">Gói học</a><a href="#availability">Lịch rảnh</a><a href="#reviews">Đánh giá</a></nav><div className="tm-detail-grid"><div className="tm-stack"><section id="about" className="tm-panel tm-section-anchor"><h2>Về gia sư</h2><p className="tm-prose">{teacher.bio||'Gia sư chưa cập nhật giới thiệu.'}</p>{teacher.introductionVideoUrl&&/^https?:\/\//.test(teacher.introductionVideoUrl)&&<a href={teacher.introductionVideoUrl} target="_blank" rel="noopener noreferrer">Xem video giới thiệu ↗</a>}</section><section id="packages" className="tm-panel tm-section-anchor"><h2>Chọn gói học</h2>{error('packages')||<><TeacherPackagesTab packages={packageData.data}/>{packageQuery.isFetching&&packagePage>0&&<Spin size="small"/>}</>} {(packageData.meta.totalPages||0)>1&&<div className="tm-pagination"><Pagination current={(packageData.meta.page||0)+1} pageSize={packageData.meta.size} total={packageData.meta.totalElements} showSizeChanger={false} onChange={n=>page('packagesPage',n,'packages')}/></div>}</section><section id="availability" className="tm-panel tm-section-anchor"><h2>Lịch rảnh trong tuần</h2><p>Lịch rảnh thể hiện thời gian gia sư có thể nhận dạy; buổi học cụ thể cần được thống nhất.</p>{error('availability')||<div className="tm-stack">{availability.length?availability.map((a,i)=><div className="tm-toolbar" key={a.id||i}><strong>{days[a.dayOfWeek]||a.dayOfWeek}</strong><span>{a.startTime.slice(0,5)} – {a.endTime.slice(0,5)}</span></div>):<p>Gia sư chưa cập nhật lịch rảnh.</p>}</div>}</section><section id="reviews" className="tm-panel tm-section-anchor"><h2>Đánh giá từ học viên</h2>{error('reviews')||<>{reviewData.data.length?reviewData.data.map(r=><article className="tm-review" key={r.id}><div className="tm-toolbar"><strong>{r.reviewerName}</strong><time>{new Date(r.createdAt).toLocaleDateString('vi-VN')}</time></div><span className="tm-star">{r.rating} ★</span><p>{r.comment}</p></article>):<p>Chưa có đánh giá.</p>}{(reviewData.meta.totalPages||0)>1&&<Pagination current={(reviewData.meta.page||0)+1} pageSize={reviewData.meta.size} total={reviewData.meta.totalElements} showSizeChanger={false} onChange={n=>page('reviewsPage',n,'reviews')}/>}</>}</section></div><aside id="trial" className="tm-panel tm-detail-aside tm-section-anchor"><h2>Bắt đầu với gia sư</h2><a className="tm-button" style={{width:'100%',marginBottom:12}} href="#packages">Xem các gói học</a><div style={{marginBottom:24}}><MessageTeacherButton teacherId={teacher.id} block/></div><h3>Yêu cầu học thử</h3><TrialRequestForm teacherId={teacher.id} subjects={subjectOptions}/></aside></div></>;
}
