package com.edtech.platform.admin.domain;

public enum AuditAction {
    TEACHER_APPROVED,
    TEACHER_REJECTED,
    SUBJECT_PROPOSAL_APPROVED,
    SUBJECT_PROPOSAL_REJECTED,
    USER_LOCKED,
    USER_UNLOCKED,
    REFUND_APPROVED,
    REFUND_REJECTED,
    REFUND_COMPLETED,
    PAYOUT_PROCESSING,
    PAYOUT_REJECTED,
    PAYOUT_COMPLETED,
    EXTENSION_APPROVED,
    EXTENSION_REJECTED,
    PLATFORM_SETTINGS_UPDATED
}
