'use client';
import {useState} from 'react';
import {useRouter,usePathname,useSearchParams} from 'next/navigation';
import {Button,Drawer,Input,Pagination,Tag} from 'antd';
import {FilterOutlined} from '@ant-design/icons';
import {TeacherFilterSidebar} from '@/features/marketplace/components/TeacherFilterSidebar';
import {TeacherSortBar} from '@/features/marketplace/components/TeacherSortBar';
import TeacherGrid from '@/features/marketplace/components/TeacherGrid';
import type {TeacherSearchParams,SubjectSummary,TeacherCard,PageMeta} from '@/shared/api/public';
export default function TeacherSearchClient({initialFilters,initialTeachers,subjects,isError=false}:{initialFilters:TeacherSearchParams;initialTeachers:{data:TeacherCard[];meta:Partial<PageMeta>};subjects:SubjectSummary[];isError?:boolean}){
 const router=useRouter();const pathname=usePathname();const search=useSearchParams();const [open,setOpen]=useState(false);
 const change=(values:Partial<TeacherSearchParams>)=>{const q=new URLSearchParams(search.toString());Object.entries(values).forEach(([key,value])=>{if(value===undefined||value===null||value==='')q.delete(key);else q.set(key,String(value));});if(!('page'in values))q.delete('page');router.push(pathname+'?'+q.toString());};
 const filter=<TeacherFilterSidebar filters={initialFilters} subjects={subjects} onChange={change} onClear={()=>router.push(pathname)}/>;
 return <><div className="tm-toolbar"><Input.Search aria-label="Tìm gia sư theo từ khóa" placeholder="Tên gia sư hoặc từ khóa" defaultValue={initialFilters.keyword} onSearch={keyword=>change({keyword})} allowClear style={{maxWidth:520}} size="large"/><Button className="tm-mobile-only" icon={<FilterOutlined/>} onClick={()=>setOpen(true)}>Bộ lọc</Button></div><div className="tm-chips" style={{marginBottom:20}}>{initialFilters.subjectId&&<Tag closable onClose={()=>change({subjectId:undefined})}>{subjects.find(s=>s.id===initialFilters.subjectId)?.name||'Môn đã chọn'}</Tag>}{initialFilters.deliveryMode&&<Tag closable onClose={()=>change({deliveryMode:undefined})}>{initialFilters.deliveryMode}</Tag>}{(initialFilters.minPrice!==undefined||initialFilters.maxPrice!==undefined)&&<Tag closable onClose={()=>change({minPrice:undefined,maxPrice:undefined})}>Giá gói: {initialFilters.minPrice?.toLocaleString('vi-VN')||'0'} – {initialFilters.maxPrice?.toLocaleString('vi-VN')||'không giới hạn'}đ</Tag>}</div><div className="tm-search-layout"><aside className="tm-filter-desktop">{filter}</aside><div><TeacherSortBar totalElements={initialTeachers.meta.totalElements||0} value={initialFilters.sort} onChange={sort=>change({sort})}/><TeacherGrid teachers={initialTeachers.data} isError={isError}/>{(initialTeachers.meta.totalPages||0)>1&&<div className="tm-pagination"><Pagination current={(initialTeachers.meta.page||0)+1} total={initialTeachers.meta.totalElements} pageSize={initialTeachers.meta.size||12} showSizeChanger={false} onChange={page=>change({page})}/></div>}</div></div><Drawer title="Lọc gia sư" open={open} onClose={()=>setOpen(false)}>{filter}<Button block onClick={()=>setOpen(false)} style={{marginTop:16}}>Xem kết quả</Button></Drawer></>;
}
