package com.edtech.platform.common.exception;

import org.springframework.http.HttpStatus;
import lombok.Getter;
import lombok.RequiredArgsConstructor;

@Getter
@RequiredArgsConstructor
public enum ErrorCode {
    VALIDATION_ERROR(HttpStatus.BAD_REQUEST, "Một hoặc nhiều trường dữ liệu không hợp lệ"),
    MALFORMED_JSON(HttpStatus.BAD_REQUEST, "JSON sai cú pháp hoặc kiểu dữ liệu"),
    UNSUPPORTED_MEDIA_TYPE(HttpStatus.UNSUPPORTED_MEDIA_TYPE, "Định dạng không hỗ trợ"),
    RESOURCE_NOT_FOUND(HttpStatus.NOT_FOUND, "Resource không tồn tại hoặc đã xóa"),
    FORBIDDEN_RESOURCE(HttpStatus.FORBIDDEN, "Không có quyền truy cập resource này"),
    DUPLICATE_RESOURCE(HttpStatus.CONFLICT, "Dữ liệu đã tồn tại và bị trùng lặp"),
    CONCURRENT_MODIFICATION(HttpStatus.CONFLICT, "Dữ liệu đã bị thay đổi bởi người khác, vui lòng tải lại"),
    IDEMPOTENCY_KEY_REQUIRED(HttpStatus.BAD_REQUEST, "Yêu cầu cần có Idempotency-Key"),
    IDEMPOTENCY_KEY_REUSED(HttpStatus.CONFLICT, "Idempotency-Key bị sử dụng lại với payload khác"),
    RATE_LIMIT_EXCEEDED(HttpStatus.TOO_MANY_REQUESTS, "Bạn thao tác quá nhanh, vui lòng thử lại sau"),
    INTERNAL_SERVER_ERROR(HttpStatus.INTERNAL_SERVER_ERROR, "Lỗi hệ thống không dự kiến"),
    EXTERNAL_SERVICE_UNAVAILABLE(HttpStatus.SERVICE_UNAVAILABLE, "Dịch vụ liên kết tạm thời không phản hồi"),
    AUTH_INVALID_CREDENTIALS(HttpStatus.UNAUTHORIZED, "Email hoặc mật khẩu không chính xác"),
    AUTH_TOKEN_MISSING(HttpStatus.UNAUTHORIZED, "Không tìm thấy access token"),
    AUTH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Token không hợp lệ"),
    AUTH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Token đã hết hạn"),
    AUTH_REFRESH_TOKEN_INVALID(HttpStatus.UNAUTHORIZED, "Refresh token không hợp lệ hoặc không tồn tại"),
    AUTH_REFRESH_TOKEN_EXPIRED(HttpStatus.UNAUTHORIZED, "Refresh token đã hết hạn"),
    AUTH_REFRESH_TOKEN_REVOKED(HttpStatus.UNAUTHORIZED, "Refresh token đã bị thu hồi"),
    AUTH_EMAIL_ALREADY_EXISTS(HttpStatus.CONFLICT, "Email này đã được đăng ký"),
    AUTH_EMAIL_NOT_VERIFIED(HttpStatus.FORBIDDEN, "Vui lòng xác minh email trước khi thao tác"),
    AUTH_PASSWORD_RESET_TOKEN_INVALID(HttpStatus.BAD_REQUEST, "Mã khôi phục không hợp lệ hoặc đã sử dụng"),
    AUTH_PASSWORD_RESET_TOKEN_EXPIRED(HttpStatus.BAD_REQUEST, "Mã khôi phục đã hết hạn"),
    AUTH_OAUTH_ROLE_REQUIRED(HttpStatus.UNPROCESSABLE_ENTITY, "Vui lòng chọn vai trò Student hoặc Teacher"),
    AUTH_OAUTH_LINK_NOT_ALLOWED(HttpStatus.CONFLICT, "Không thể tự động liên kết tài khoản khi email chưa xác minh"),
    ACCOUNT_LOCKED(HttpStatus.FORBIDDEN, "Tài khoản của bạn đã bị khóa"),
    ACCOUNT_DISABLED(HttpStatus.FORBIDDEN, "Tài khoản của bạn đã bị vô hiệu hóa"),
    ACCOUNT_NOT_ACTIVE(HttpStatus.FORBIDDEN, "Tài khoản của bạn chưa kích hoạt"),
    ROLE_NOT_ALLOWED(HttpStatus.FORBIDDEN, "Bạn không có quyền thực hiện chức năng này"),
    TEACHER_PROFILE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy hồ sơ giáo viên"),
    TEACHER_NOT_APPROVED(HttpStatus.FORBIDDEN, "Giáo viên chưa được duyệt"),
    TEACHER_PROFILE_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái hồ sơ không hợp lệ cho thao tác này"),
    TEACHER_DOCUMENT_NOT_DELETABLE(HttpStatus.UNPROCESSABLE_ENTITY, "Không thể xóa chứng chỉ này"),
    SUBJECT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy môn học"),
    SUBJECT_INACTIVE(HttpStatus.UNPROCESSABLE_ENTITY, "Môn học đã ngừng hoạt động"),
    SUBJECT_NOT_ASSIGNED(HttpStatus.UNPROCESSABLE_ENTITY, "Giáo viên chưa được gán môn học này"),
    SUBJECT_ALREADY_ASSIGNED(HttpStatus.CONFLICT, "Môn học này đã được gán cho giáo viên"),
    SUBJECT_CODE_ALREADY_EXISTS(HttpStatus.CONFLICT, "Mã môn học đã tồn tại"),
    SUBJECT_SLUG_ALREADY_EXISTS(HttpStatus.CONFLICT, "Slug môn học đã tồn tại"),
    SUBJECT_PROPOSAL_INVALID_STATE(HttpStatus.BAD_REQUEST, "Đề xuất môn học không còn ở trạng thái chờ duyệt"),
    AVAILABILITY_TIME_CONFLICT(HttpStatus.CONFLICT, "Khoảng thời gian bị trùng lặp"),
    AVAILABILITY_INVALID_RANGE(HttpStatus.BAD_REQUEST, "Khoảng thời gian không hợp lệ"),
    PRICING_PACKAGE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy gói học"),
    PACKAGE_NOT_ACTIVE(HttpStatus.UNPROCESSABLE_ENTITY, "Gói học không ở trạng thái hoạt động"),
    PACKAGE_IMMUTABLE_AFTER_PURCHASE(HttpStatus.UNPROCESSABLE_ENTITY, "Không thể thay đổi gói học đã có người mua"),
    PACKAGE_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY, "Gói học của học viên đã hết hạn"),
    PACKAGE_NO_REMAINING_SESSION(HttpStatus.UNPROCESSABLE_ENTITY, "Gói học đã hết số buổi"),
    PACKAGE_HAS_SCHEDULED_BOOKING(HttpStatus.UNPROCESSABLE_ENTITY, "Vẫn còn buổi học đang được lên lịch"),
    PACKAGE_COUNTER_INVARIANT_VIOLATION(HttpStatus.INTERNAL_SERVER_ERROR, "Dữ liệu đếm số buổi không khớp"),
    PACKAGE_BOOKING_END_AFTER_EXPIRY(HttpStatus.UNPROCESSABLE_ENTITY, "Thời gian buổi học vượt quá hạn của gói"),
    PACKAGE_RELATION_MISMATCH(HttpStatus.FORBIDDEN, "Gói học không thuộc về bạn"),
    PACKAGE_REFUND_IN_PROGRESS(HttpStatus.UNPROCESSABLE_ENTITY, "Gói học đang có yêu cầu hoàn tiền"),
    PACKAGE_EXTENSION_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "Chỉ gia hạn được gói học đã hết hạn"),
    PACKAGE_EXTENSION_DATE_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "Ngày gia hạn mới không hợp lệ"),
    BOOKING_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy buổi học"),
    BOOKING_TIME_CONFLICT(HttpStatus.CONFLICT, "Trùng lịch học viên hoặc giáo viên"),
    BOOKING_INVALID_TIME_RANGE(HttpStatus.BAD_REQUEST, "Khoảng thời gian buổi học không hợp lệ"),
    BOOKING_IN_PAST(HttpStatus.UNPROCESSABLE_ENTITY, "Không thể đặt lịch trong quá khứ"),
    BOOKING_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái buổi học không hợp lệ"),
    BOOKING_REPORT_REQUIRED(HttpStatus.BAD_REQUEST, "Bắt buộc phải có báo cáo buổi học"),
    BOOKING_NOT_ENDED(HttpStatus.UNPROCESSABLE_ENTITY, "Không thể hoàn thành buổi học chưa kết thúc"),
    BOOKING_CANCEL_REASON_REQUIRED(HttpStatus.BAD_REQUEST, "Bắt buộc phải có lý do hủy"),
    BOOKING_STUDENT_CANCEL_NOT_ALLOWED(HttpStatus.FORBIDDEN, "Học viên không được quyền tự hủy"),
    BOOKING_SETTLEMENT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "Thanh toán cho buổi học đã được xử lý"),
    TRIAL_ALREADY_USED(HttpStatus.UNPROCESSABLE_ENTITY, "Học viên đã học thử với giáo viên này"),
    TRIAL_REQUEST_ALREADY_PENDING(HttpStatus.CONFLICT, "Học viên đã có yêu cầu học thử đang chờ"),
    TRIAL_REQUEST_INVALID_STATE(HttpStatus.BAD_REQUEST, "Yêu cầu học thử không ở trạng thái hợp lệ"),
    TRIAL_PACKAGE_NOT_ALLOWED(HttpStatus.BAD_REQUEST, "Học thử không được dùng chung với gói học hiện có"),
    SESSION_REPORT_ALREADY_EXISTS(HttpStatus.CONFLICT, "Buổi học này đã có báo cáo"),
    REVIEW_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "Chưa được phép đánh giá buổi học này"),
    REVIEW_ALREADY_EXISTS(HttpStatus.CONFLICT, "Buổi học này đã được đánh giá"),
    REVIEW_RATING_INVALID(HttpStatus.BAD_REQUEST, "Điểm đánh giá không hợp lệ"),
    INVOICE_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy hóa đơn"),
    INVOICE_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái hóa đơn không hợp lệ"),
    INVOICE_EXPIRED(HttpStatus.UNPROCESSABLE_ENTITY, "Hóa đơn đã hết hạn thanh toán"),
    PAYMENT_AMOUNT_MISMATCH(HttpStatus.UNPROCESSABLE_ENTITY, "Số tiền thanh toán không khớp"),
    PAYMENT_SIGNATURE_INVALID(HttpStatus.UNAUTHORIZED, "Chữ ký thanh toán không hợp lệ"),
    PAYMENT_ALREADY_PROCESSED(HttpStatus.CONFLICT, "Thanh toán này đã được xử lý"),
    PAYMENT_LINK_CREATION_FAILED(HttpStatus.BAD_GATEWAY, "Không thể tạo link thanh toán"),
    PAYMENT_PROVIDER_ERROR(HttpStatus.BAD_GATEWAY, "Lỗi từ nhà cung cấp dịch vụ thanh toán"),
    PAYMENT_RECONCILIATION_FAILED(HttpStatus.BAD_GATEWAY, "Đối soát thanh toán thất bại"),
    WALLET_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy ví"),
    WALLET_BALANCE_INVARIANT_VIOLATION(HttpStatus.INTERNAL_SERVER_ERROR, "Số dư ví không hợp lệ"),
    LEDGER_DUPLICATE_ENTRY(HttpStatus.CONFLICT, "Giao dịch đã tồn tại"),
    BANK_ACCOUNT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy tài khoản ngân hàng"),
    BANK_ACCOUNT_NOT_VERIFIED(HttpStatus.UNPROCESSABLE_ENTITY, "Tài khoản ngân hàng chưa được xác minh"),
    BANK_ACCOUNT_IN_USE(HttpStatus.CONFLICT, "Tài khoản ngân hàng đang được sử dụng"),
    PAYOUT_INSUFFICIENT_BALANCE(HttpStatus.UNPROCESSABLE_ENTITY, "Số dư không đủ để rút"),
    PAYOUT_INVALID_AMOUNT(HttpStatus.BAD_REQUEST, "Số tiền rút không hợp lệ"),
    PAYOUT_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái yêu cầu rút tiền không hợp lệ"),
    PAYOUT_PROOF_REQUIRED(HttpStatus.BAD_REQUEST, "Bắt buộc có minh chứng thanh toán"),
    PAYOUT_ALREADY_PENDING(HttpStatus.UNPROCESSABLE_ENTITY, "Đã có yêu cầu rút tiền đang xử lý"),
    REFUND_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy yêu cầu hoàn tiền"),
    REFUND_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái hoàn tiền không hợp lệ"),
    REFUND_AMOUNT_EXCEEDED(HttpStatus.UNPROCESSABLE_ENTITY, "Số lượng hoặc số tiền hoàn vượt quá cho phép"),
    REFUND_NO_REMAINING_SESSION(HttpStatus.UNPROCESSABLE_ENTITY, "Không còn buổi nào để hoàn tiền"),
    REFUND_ALREADY_PENDING(HttpStatus.CONFLICT, "Gói học này đang có yêu cầu hoàn tiền khác"),
    REFUND_PROOF_REQUIRED(HttpStatus.BAD_REQUEST, "Bắt buộc có minh chứng hoàn tiền"),
    REFUND_WALLET_INSUFFICIENT(HttpStatus.UNPROCESSABLE_ENTITY, "Số dư ví không đủ để xử lý hoàn tiền"),
    EXTENSION_REQUEST_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy yêu cầu gia hạn"),
    EXTENSION_REQUEST_ALREADY_PENDING(HttpStatus.CONFLICT, "Đã có yêu cầu gia hạn đang xử lý"),
    EXTENSION_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái yêu cầu gia hạn không hợp lệ"),
    ASSIGNMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bài tập"),
    ASSIGNMENT_INVALID_STATE(HttpStatus.BAD_REQUEST, "Trạng thái bài tập không hợp lệ"),
    ASSIGNMENT_DUE_DATE_PASSED(HttpStatus.UNPROCESSABLE_ENTITY, "Đã quá hạn nộp bài"),
    SUBMISSION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy bài nộp"),
    SUBMISSION_ALREADY_GRADED(HttpStatus.CONFLICT, "Bài nộp đã được chấm điểm"),
    SUBMISSION_NOT_SUBMITTED(HttpStatus.UNPROCESSABLE_ENTITY, "Bài nộp chưa được gửi"),
    FILE_TYPE_NOT_ALLOWED(HttpStatus.UNPROCESSABLE_ENTITY, "Định dạng file không được phép"),
    FILE_TOO_LARGE(HttpStatus.PAYLOAD_TOO_LARGE, "Dung lượng file vượt giới hạn"),
    FILE_UPLOAD_FAILED(HttpStatus.BAD_GATEWAY, "Lỗi upload file"),
    ATTACHMENT_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy tệp đính kèm"),
    ATTACHMENT_CONTEXT_INVALID(HttpStatus.UNPROCESSABLE_ENTITY, "Bối cảnh đính kèm không hợp lệ"),
    CONVERSATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy cuộc trò chuyện"),
    CONVERSATION_NOT_ALLOWED(HttpStatus.FORBIDDEN, "Chưa được phép trò chuyện"),
    MESSAGE_TYPE_INVALID(HttpStatus.BAD_REQUEST, "Loại tin nhắn không hợp lệ"),
    MESSAGE_DUPLICATE(HttpStatus.CONFLICT, "Tin nhắn bị lặp lại"),
    NOTIFICATION_NOT_FOUND(HttpStatus.NOT_FOUND, "Không tìm thấy thông báo");

    private final HttpStatus status;
    private final String defaultMessage;
}
