'use client';
import {useRef,useState} from 'react';
import {usePathname,useRouter} from 'next/navigation';
import {App,Button,Modal} from 'antd';
import type {PricingPackageView} from '@/shared/api/public';
import {useAuthStore} from '@/features/auth';
import {paymentApi} from '@/features/payments/api/paymentApi';
export function TeacherPackagesTab({packages}:{packages:PricingPackageView[]}){
 const {user}=useAuthStore();const router=useRouter();const pathname=usePathname();const {message}=App.useApp();const [selected,setSelected]=useState<PricingPackageView|null>(null);const [busy,setBusy]=useState(false);const key=useRef<string|null>(null);
 const choose=(pkg:PricingPackageView)=>{if(!user){router.push('/auth/login?redirect='+encodeURIComponent(pathname+'?packageId='+pkg.id+'#packages'));return;}if(user.role!=='STUDENT')return;key.current=crypto.randomUUID();setSelected(pkg);};
 const buy=async()=>{if(!selected||busy)return;setBusy(true);try{const callback=window.location.origin+'/student/payments/callback';const res=await paymentApi.createInvoice({pricingPackageId:selected.id,returnUrl:callback,cancelUrl:callback},key.current!);if(!res.data.id)throw new Error('Chưa nhận được mã hóa đơn.');router.push('/student/checkout/'+res.data.id);}catch(e){message.error(e instanceof Error?e.message:'Chưa tạo được hóa đơn. Thử lại với cùng yêu cầu.');}finally{setBusy(false);}};
 if(!packages.length)return <p>Gia sư chưa mở gói học. Bạn có thể xem lịch rảnh và gửi yêu cầu học thử.</p>;
 return <><div className="tm-package-grid">{packages.map(pkg=><article className="tm-package" key={pkg.id}><span className="tm-chip">{pkg.subjectName||'Gói học 1–1'}</span><h3>{pkg.name}</h3>{pkg.description&&<p>{pkg.description}</p>}<div>{pkg.totalSessions??pkg.sessionCount} buổi · {pkg.sessionDurationMinutes??pkg.durationMinutes} phút/buổi{pkg.durationDays&&<p>Hạn sử dụng: {pkg.durationDays} ngày</p>}</div><div className="tm-package-price">{new Intl.NumberFormat('vi-VN').format(pkg.priceVnd)}đ <small style={{fontSize:12,fontWeight:400}}>trọn gói</small></div>{(!user||user.role==='STUDENT')&&<Button type="primary" size="large" onClick={()=>choose(pkg)}>Chọn gói học</Button>}</article>)}</div><Modal open={!!selected} title="Xác nhận gói học" onCancel={()=>{if(!busy)setSelected(null);}} onOk={buy} confirmLoading={busy} okText="Tạo hóa đơn thanh toán" cancelText="Quay lại" closable={!busy} mask={{closable:!busy}}>{selected&&<><h3>{selected.name}</h3><p>{selected.totalSessions??selected.sessionCount} buổi · {selected.sessionDurationMinutes??selected.durationMinutes} phút/buổi</p><p>Giá trọn gói: <strong>{new Intl.NumberFormat('vi-VN').format(selected.priceVnd)}đ</strong></p><p>Sau khi thanh toán được xác nhận, gói học sẽ xuất hiện trong tài khoản. Gia sư sẽ thống nhất và tạo lịch học.</p></>}</Modal></>;
}
