package com.edtech.platform.finance.domain;
public enum LedgerEntryType {
    PACKAGE_FUNDED, SESSION_RELEASE_PENDING, SESSION_CREDIT_AVAILABLE,
    SESSION_ESCROW_HELD, SESSION_ESCROW_RELEASED, COMMISSION_RECOGNIZED,
    PAYOUT_RESERVED, PAYOUT_SUCCEEDED, PAYOUT_RELEASED, REFUND_DEBIT_PENDING, ADJUSTMENT
}
